# Действия связанные с дискордом
discord:
  # Токен бота
  token: ""
  # Айди канала в котором надо будет вводить ник
  channel_id: ""
  # Айди роли которая будет выдаваться
  role_id: ""
  # Сообщение которое отправится в ЛС игроку при успешной верификации
  success_message: "**Верификация успешно пройдена!**"
  # Сообщение которое отправится в ЛС игроку при ошибке
  error_message: "**Похоже что вы неправильно ввели свой ник, ник должен состоять из одного слова**"

# Действия связанные с майнкрафтом
minecraft:
  # Сообщение которое будет писаться при перезагруке конфига
  reload: "&bКонфиг перезагружен!"
  # Команда которая будет выполняться при прохождении верификации
  command: "whitelist add %player%"